// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCIbfRXWABRN60KlaYHu37PolVrWpPHjmY",
    appId: '1:60905720073:web:a8a6603e104ac71863abd8',
    authDomain: "flash-chat-94457.firebaseapp.com",
    projectId: "flash-chat-94457",
    storageBucket: "flash-chat-94457.appspot.com",
    messagingSenderId: "60905720073",
    measurementId: "G-8J10W9D7H0"
  );



  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_i03Akpd_XlrxvEmukfHyTKuJMh31J-Y',
    appId: '1:60905720073:android:af78cda96393e18763abd8',
    messagingSenderId: '60905720073',
    projectId: 'flash-chat-94457',
    storageBucket: 'flash-chat-94457.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLccjmZp1dLWRt6gXIJgm1CCM2q1KEFeo',
    appId: '1:60905720073:ios:fdc79ce3e61883aa63abd8',
    messagingSenderId: '60905720073',
    projectId: 'flash-chat-94457',
    storageBucket: 'flash-chat-94457.appspot.com',
    iosBundleId: 'co.appbrewery.flashChat',
  );
}
